//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHC.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabTestDetail
    {
        public string LabTestDetailID { get; set; }
        public string PatientPrescriptionID { get; set; }
        public string LabTestID { get; set; }
        public string PHCID { get; set; }
        public string Result { get; set; }
        public string Remarks { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string ObsInd { get; set; }
    
        public virtual MLabTest MLabTest { get; set; }
        public virtual MPHC MPHC { get; set; }
        public virtual PatientPrescription PatientPrescription { get; set; }
    }
}
