//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHC.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDrug
    {
        public MDrug()
        {
            this.DrugsIssueds = new HashSet<DrugsIssued>();
        }
    
        public string DrugID { get; set; }
        public string Name { get; set; }
        public int Quantity { get; set; }
        public string BatchNo { get; set; }
        public System.DateTime manufactureDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string ObsInd { get; set; }
        public string State { get; set; }
    
        public virtual ICollection<DrugsIssued> DrugsIssueds { get; set; }
    }
}
