//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHC.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPHC
    {
        public MPHC()
        {
            this.DrugsIssueds = new HashSet<DrugsIssued>();
            this.LabTestDetails = new HashSet<LabTestDetail>();
            this.MVillages = new HashSet<MVillage>();
            this.PatientDetails = new HashSet<PatientDetail>();
            this.PatientPrescriptions = new HashSet<PatientPrescription>();
            this.UserMaps = new HashSet<UserMap>();
            this.DrugStockDetails = new HashSet<DrugStockDetail>();
            this.PatientECs = new HashSet<PatientEC>();
            this.PatientMCs = new HashSet<PatientMC>();
            this.SubCenters = new HashSet<SubCenter>();
            this.PHCTransactions = new HashSet<PHCTransaction>();
            this.VaccinationHistories = new HashSet<VaccinationHistory>();
        }
    
        public string PHCID { get; set; }
        public string TalukID { get; set; }
        public string Name { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string ObsInd { get; set; }
    
        public virtual ICollection<DrugsIssued> DrugsIssueds { get; set; }
        public virtual ICollection<LabTestDetail> LabTestDetails { get; set; }
        public virtual MTaluk MTaluk { get; set; }
        public virtual ICollection<MVillage> MVillages { get; set; }
        public virtual ICollection<PatientDetail> PatientDetails { get; set; }
        public virtual ICollection<PatientPrescription> PatientPrescriptions { get; set; }
        public virtual ICollection<UserMap> UserMaps { get; set; }
        public virtual ICollection<DrugStockDetail> DrugStockDetails { get; set; }
        public virtual ICollection<PatientEC> PatientECs { get; set; }
        public virtual ICollection<PatientMC> PatientMCs { get; set; }
        public virtual ICollection<SubCenter> SubCenters { get; set; }
        public virtual ICollection<PHCTransaction> PHCTransactions { get; set; }
        public virtual ICollection<VaccinationHistory> VaccinationHistories { get; set; }
    }
}
