//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHC.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientDetail
    {
        public PatientDetail()
        {
            this.PatientAddresses = new HashSet<PatientAddress>();
            this.PatientECs = new HashSet<PatientEC>();
            this.PatientMCs = new HashSet<PatientMC>();
            this.PatientPrescriptions = new HashSet<PatientPrescription>();
            this.PHCTransactions = new HashSet<PHCTransaction>();
        }
    
        public string PatientID { get; set; }
        public string PHCID { get; set; }
        public string Name { get; set; }
        public short age { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Sex { get; set; }
        public string BloodGroup { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string ObsInd { get; set; }
        public string ReligionID { get; set; }
        public string EducationID { get; set; }
    
        public virtual MPHC MPHC { get; set; }
        public virtual ICollection<PatientAddress> PatientAddresses { get; set; }
        public virtual ICollection<PatientEC> PatientECs { get; set; }
        public virtual ICollection<PatientMC> PatientMCs { get; set; }
        public virtual ICollection<PatientPrescription> PatientPrescriptions { get; set; }
        public virtual ICollection<PHCTransaction> PHCTransactions { get; set; }
        public virtual MEducation MEducation { get; set; }
        public virtual MReligion MReligion { get; set; }
    }
}
