//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHC.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientPrescription
    {
        public PatientPrescription()
        {
            this.DrugsIssueds = new HashSet<DrugsIssued>();
            this.LabTestDetails = new HashSet<LabTestDetail>();
        }
    
        public string PrescriptionID { get; set; }
        public string PatientID { get; set; }
        public string PHCID { get; set; }
        public string DiseaseID { get; set; }
        public string Description { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string ObsInd { get; set; }
    
        public virtual ICollection<DrugsIssued> DrugsIssueds { get; set; }
        public virtual ICollection<LabTestDetail> LabTestDetails { get; set; }
        public virtual MDisease MDisease { get; set; }
        public virtual MPHC MPHC { get; set; }
        public virtual PatientDetail PatientDetail { get; set; }
    }
}
