//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHC.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PHCSolutions : DbContext,IUnitOfWork
    {
        public PHCSolutions()
            : base("name=PHCSolutions")
        {
            this.Configuration.LazyLoadingEnabled = true;
            this.Configuration.ProxyCreationEnabled = true;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DrugsIssued> DrugsIssueds { get; set; }
        public DbSet<LabTestDetail> LabTestDetails { get; set; }
        public DbSet<MDisease> MDiseases { get; set; }
        public DbSet<MDistrict> MDistricts { get; set; }
        public DbSet<MDrug> MDrugs { get; set; }
        public DbSet<MLabTest> MLabTests { get; set; }
        public DbSet<MPHC> MPHCs { get; set; }
        public DbSet<MState> MStates { get; set; }
        public DbSet<MTaluk> MTaluks { get; set; }
        public DbSet<MVillage> MVillages { get; set; }
        public DbSet<PatientAddress> PatientAddresses { get; set; }
        public DbSet<PatientDetail> PatientDetails { get; set; }
        public DbSet<PatientEC> PatientECs { get; set; }
        public DbSet<PatientMC> PatientMCs { get; set; }
        public DbSet<PatientPrescription> PatientPrescriptions { get; set; }
        public DbSet<UserDetail> UserDetails { get; set; }
        public DbSet<UserMap> UserMaps { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public DbSet<AspNetRole> AspNetRoles { get; set; }
        public DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public DbSet<AspNetUser> AspNetUsers { get; set; }
        public DbSet<DrugStockDetail> DrugStockDetails { get; set; }
        public DbSet<MEducation> MEducations { get; set; }
        public DbSet<MReligion> MReligions { get; set; }
        public DbSet<MScheme> MSchemes { get; set; }
        public DbSet<SubCenter> SubCenters { get; set; }
        public DbSet<MVaccination> MVaccinations { get; set; }
        public DbSet<PHCTransaction> PHCTransactions { get; set; }
        public DbSet<VaccinationHistory> VaccinationHistories { get; set; }

        public void Save()
        {
            base.SaveChanges();
        }
    }
}
