//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHC.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHCTransaction
    {
        public string PHCTransactionID { get; set; }
        public string PHCID { get; set; }
        public string SchemeID { get; set; }
        public string PatientID { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<decimal> ReceivedAmount { get; set; }
        public Nullable<decimal> SpentAmount { get; set; }
        public string ISDebited { get; set; }
        public string Description { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string ObsInd { get; set; }
        public string HandOver { get; set; }
        public string ReceivedFrom { get; set; }
        public string TransactionType { get; set; }
    
        public virtual MPHC MPHC { get; set; }
        public virtual MScheme MScheme { get; set; }
        public virtual PatientDetail PatientDetail { get; set; }
    }
}
