//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PHC.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMap
    {
        public string UserMapID { get; set; }
        public string UserID { get; set; }
        public string StateID { get; set; }
        public string DistrictID { get; set; }
        public string TalukID { get; set; }
        public string PHCID { get; set; }
        public string VillageID { get; set; }
        public string DisplayName { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string ObsInd { get; set; }
    
        public virtual MDistrict MDistrict { get; set; }
        public virtual MPHC MPHC { get; set; }
        public virtual MState MState { get; set; }
        public virtual MTaluk MTaluk { get; set; }
        public virtual MVillage MVillage { get; set; }
        public virtual User User { get; set; }
    }
}
